"""auto add likes table

Revision ID: f82c935c2543
Revises: 005973fa6a00
Create Date: 2023-02-28 18:16:13.764968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82c935c2543'
down_revision = '005973fa6a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_LIKES',
    sa.Column('LIK_POS_ID', sa.Integer(), nullable=False),
    sa.Column('LIK_USU_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LIK_POS_ID'], ['T_POSTS.POS_ID'], ),
    sa.ForeignKeyConstraint(['LIK_USU_ID'], ['T_USUARIOS.USU_ID'], ),
    sa.PrimaryKeyConstraint('LIK_POS_ID', 'LIK_USU_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_LIKES')
    # ### end Alembic commands ###
